<?php
return array (
  'mxprocms' => 
  array (
    's1' => 
    array (
      'logo1' => 'mxtheme/images/logo.png',
      'logo2' => 'mxtheme/images/logo_black.png',
      'ico' => 'mxtheme/images/favicon.png',
      'pic' => 'mxtheme/images/load.gif',
      'userbg' => 'mxtheme/images/userbg.jpg',
      'errorpic' => 'mxtheme/images/errorpic.png',
      'searchwd' => '搜索电影、电视剧、综艺、动漫',
      'sm' => '本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务',
    ),
    's2' => 
    array (
      'notourlgid' => '',
      'theme' => 'white',
      'searchtips' => '1',
      'douban' => '1',
      'doubanpingfen' => '1',
      'daohanztjc' => '1',
      'dbmap' => '1',
      'dbfk' => '1',
      'dbfktext' => 'IF101高清免费无广资源站',
      'dbfkurl' => 'https://demo.if101.tv/',
      'qqqun' => '1',
      'qqquntext' => 'IF101TG群',
      'qqqunurl' => 'https://t.me/if101tv',
      'telegram' => '1',
      'telegramtext' => 'IF101超级播放器',
      'telegramurl' => 'https://t.me/if101tv/58529',
      'daohangid' => 'parent',
      'iconmr' => 'icon-jl-o',
      'num1' => '1',
      'icon1' => 'icon-dy-o',
      'num2' => '2',
      'icon2' => 'icon-tv-o',
      'num3' => '3',
      'icon3' => 'icon-zy-o',
      'num4' => '4',
      'icon4' => 'icon-dm-o',
      'num5' => '',
      'icon5' => 'icon-jl-o',
      'num6' => '',
      'icon6' => '',
      'num7' => '',
      'icon7' => '',
      'diy1' => '0',
      'diy1name' => '觅知',
      'diy1url' => 'https://www.98dou.cn/',
      'diy1icon' => 'icon-diy',
      'diy2' => '0',
      'diy2name' => '觅知',
      'diy2url' => 'https://www.98dou.cn/',
      'diy2icon' => 'icon-diy',
      'wapdaohangid' => '1,2,3,4,5',
      'wapiconmr' => '',
      'wapnum1' => '1',
      'wapicon1' => 'icon-dy-o',
      'wapnum2' => '2',
      'wapicon2' => 'icon-tv-o',
      'wapnum3' => '3',
      'wapicon3' => 'icon-zy-o',
      'wapnum4' => '4',
      'wapicon4' => 'icon-dm-o',
      'wapnum5' => '5',
      'wapicon5' => 'icon-bilibili',
      'wapdiy1' => '1',
      'wapdiy1name' => '觅知',
      'wapdiy1url' => 'https://www.98dou.cn/',
      'wapdiy1icon' => 'icon-windows',
      'wapdiy2' => '0',
      'wapdiy2name' => '觅知',
      'wapdiy2url' => 'https://www.98dou.cn/',
      'wapdiy2icon' => 'icon-diy',
      'todaynew' => '1',
      'navhot' => '1',
      'week' => '1',
      'diyheaddm' => '',
      'diy2headdm' => '',
      'app' => '1',
      'target' => '1',
      'appname' => 'APP',
      'appurl' => '/index.php/label/down.html',
      'appicon' => 'icon-phone-o',
      'hturl' => '',
      'zongkg' => '1',
      'gbook' => '1',
      'edit' => '1',
      'up' => '1',
      'jianfan' => '1',
      'themekg' => '1',
      'searchdbphb' => '1',
      'searchdbphbtext' => '热搜榜',
      'searchdbphburl' => '/index.php/label/hot.html',
      'bftips1' => '请勿轻易相信视频中的任何广告，谨防上当受骗',
      'bftips2' => '如遇视频无法播放或加载速度慢，可尝试切换播放节点或者切换解析',
      'descdswz' => '扫码支付打赏任意金额',
      'descdsm' => '/mxtheme/images/dsqrcode.jpg',
    ),
    's4' => 
    array (
      'dbdh' => '1',
      'apptxt' => '觅知Mxone Pro网站APP',
      'appentxt' => '海量高清影片、更佳观影体验，尽在Mxone Pro APP',
      'android' => '1',
      'androidtxt' => 'Android版',
      'androidurl' => 'https://www.98dou.cn/',
      'androidicon' => 'icon-android',
      'ios' => '1',
      'iostxt' => 'ios版',
      'iosurl' => 'https://www.98dou.cn/',
      'iosicon' => 'icon-apple',
      'win' => '1',
      'wintxt' => '客户端版',
      'winurl' => 'https://www.98dou.cn/',
      'winicon' => 'icon-windows',
      'appewm' => 'mxtheme/images/ewm.png',
      'liketext' => '相关推荐',
      'liketexteg' => 'TUIJIAN',
      'likeyear' => '2022',
      'likenum' => '16',
      'sort' => '1',
      'thenext' => '1',
      'share' => '1',
      'report' => '1',
      'phone' => '1',
      'miniplay' => '1',
      'qrcodetips' => '被部分浏览器误屏蔽，为保证正常访问，推荐使用<strong>Chrome</strong>、<strong>Edge</strong>、<strong>Safari</strong>等浏览器。 ',
      'copyrighttxt' => '应版权方要求该资源已下架',
      'type' => '1',
      'typelevel' => '0',
      'typeby' => 'time',
      'typeyear' => '2022',
      'typenum' => '10',
      'type1' => '1',
      'typetext' => '新片上线',
      'typetexteg' => 'NEW FILM ONLINE',
      'typeby1' => 'time',
      'typeyear1' => '2022',
      'typenum1' => '16',
      'typestart' => '9',
      'type2' => '1',
      'typetext1' => '排行榜',
      'typetexteg1' => 'RANKING',
      'typeyear2' => '',
      'typenum2' => '16',
      'type3' => '1',
      'typetext2' => '最近更新',
      'typetexteg2' => 'LATEST UPDATE',
      'typeby3' => 'time',
      'typeyear3' => '',
      'typenum3' => '16',
      'actortext' => '211',
      'actornum' => '16',
      'actor1text' => '内地,韩国,香港,日本,美国,欧洲,英国,台湾',
      'actor1num' => '',
      'ypktxet' => '72',
      'showclass' => '1',
      'showjq' => '1',
      'showarea' => '1',
      'showyear' => '1',
      'showlang' => '1',
      'showzm' => '1',
      'showby' => '1',
      'newtext' => '今日更新',
      'newby' => 'time',
      'neworder' => 'desc',
      'newyear' => '2022',
      'newnum' => '48',
      'newtext1' => '新片上线',
      'newby1' => 'time',
      'neworder1' => 'desc',
      'newyear1' => '2022',
      'newnum1' => '48',
      'hottext' => '最近热门',
      'hotby' => 'hits',
      'hotorder' => 'desc',
      'hotyear' => '',
      'hotnum' => '48',
      'hottext1' => '近期热门',
      'hotby1' => 'hits',
      'hotorder1' => 'desc',
      'hotyear1' => '2022',
      'hotnum1' => '48',
    ),
    's3' => 
    array (
      'slide' => '1',
      'slidebill' => '1',
      'slidetj' => '9',
      'slidenum' => '10',
      'slideby' => 'time',
      'slideorder' => 'desc',
      'slidefb' => '1',
      'indexweektext' => '追剧周表',
      'indexweektextfbt' => '',
      'indexweeknumsy' => '',
      'indexweeknum' => '',
      'indextopic' => '1',
      'indextopictext' => '专题',
      'indextopiceg' => 'ZHUANTI',
      'indextopicnum' => '',
      'indexart' => '1',
      'indexartdh' => '1',
      'indexarurl' => '/index.php/art/type/id/7.html',
      'indexarttext' => '资讯',
      'indexarteg' => 'ZIXUN',
      'indexartnum' => '',
      'indexhot' => '1',
      'indexhotpic' => '1',
      'indexhottext' => '正在热映',
      'indexhottextfbt' => '',
      'indexhottj' => '1',
      'indexhotnum' => '16',
      'indexlist' => '1',
      'indexlistid' => 'parent',
      'indexlistnum1' => '16',
      'indexlistby1' => 'time',
      'indexlistyear1' => '2022',
      'indexlistorder1' => 'desc',
      'indextop' => '1',
      'indextopid' => 'parent',
      'indextoptext' => '热榜',
      'indextopeg' => 'RANKING',
      'indextopnum' => '10',
      'indextopby' => 'hits',
      'indextopyear' => '2022',
      'indextoporder' => 'desc',
      'indexlink' => '1',
      'indexlinknum' => '99',
      'indexactordh' => '1',
      'indexactorurl' => '/index.php/actor/type/id/6.html',
    ),
    's5' => 
    array (
      'notice' => '1',
      'noticetext' => '公告内容',
      'noticecontent' => '<strong><p>◆欢迎使用2022 觅知MxPro 系列影视模板</p>
<p>◆本模板由觅知博客(www.98dou.cn)优化重制作</p>
<p>◆最新版本觅知现已更新至MxPro V4.0+</p>
<p>◆觅知承诺源代码无任何外链以及无后门</p></strong>
<br/>1.化繁为简<br/>2.全新框架全新UI<br/>3.去除多余繁杂的页面和功能给你一款简约清新的模板<br/>4.觅知新增众多新功能，详情请访问觅知博客更新记录<br/>更多功能查看后台请慢慢体验！！！',
      'bftip' => '1',
      'descds' => '1',
      'shier' => '1',
      'ctrl' => '1',
      'right' => '1',
      'mode' => '1',
      'pbtips' => '你知道的太多了',
      'tbdmtips' => '',
      'dbdmtips' => '',
      'stylecss' => '',
    ),
    's6' => 
    array (
      'adsindexdm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
      'adsindexlistdm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
      'adsdetdm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
      'adsplaydm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
      'adsplaybfqdm' => '<div class="player-rm rm-two rm-list">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg" alt="觅知博客" width="100%"></a>
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg" alt="觅知博客" width="100%"></a>',
      'adssearchdm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
      'adsscreendm' => '<div class="module-adslist  ads_w">
<a target="_blank" href="https://www.98dou.cn/3815.html"><img src="https://pic3.iqiyipic.com/image/20220706/06/b8/pv_10007589074_em_601.jpg?caplist=jpg,webp" alt="文本" width="100%"><i class="gg-icon"></i></a>
</div>',
    ),
  ),
);